observeEvent(input$replot, {
    disable("replot")
    html("replot", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
    hide("sep_exchange_frequency")
    hide("sep_compliance")
    hide("sep_start_time")
    hide("art_start_time")
    hide("art_number")
    hide("art_rate")
    hide("prep_number")
    hide("prep_start_time")
    hide("prep_rate")
})



observeEvent(input$actionM1, {
    disable("actionM1")
    html("actionM1", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
    hide("sep_exchange_frequency1")
    hide("sep_compliance1")
    hide("sep_start_time1")
    hide("art_start_time1")
    hide("art_number1")
    hide("art_rate1")
    hide("prep_number1")
    hide("prep_start_time1")
    hide("prep_rate1")
})


observeEvent(input$actionM2, {
    disable("actionM2")
    html("actionM2", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
    hide("sep_exchange_frequency2")
    hide("sep_compliance2")
    hide("sep_start_time2")
    hide("art_start_time2")
    hide("art_number2")
    hide("art_rate2")
    hide("prep_number2")
    hide("prep_start_time2")
    hide("prep_rate2")
})
observeEvent(input$actionM3, {
    disable("actionM3")
    html("actionM3", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
    hide("sep_exchange_frequency3")
    hide("sep_compliance3")
    hide("sep_start_time3")
    hide("art_start_time3")
    hide("art_number3")
    hide("art_rate3")
    hide("prep_number3")
    hide("prep_start_time3")
    hide("prep_rate3")
})
observeEvent(input$actionM4, {
    disable("actionM4")
    hide("sep_exchange_frequency4")
    hide("sep_compliance4")
    hide("sep_start_time4")
    hide("art_start_time4")
    hide("art_number4")
    hide("art_rate4")
    hide("prep_number4")
    hide("prep_start_time4")
    hide("prep_rate4")
    html("actionM4", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
})
observeEvent(input$actionM5, {
    disable("actionM5")
    hide("sep_exchange_frequency5")
    hide("sep_compliance5")
    hide("sep_start_time5")
    hide("art_start_time5")
    hide("art_number5")
    hide("art_rate5")
    hide("prep_number5")
    hide("prep_start_time5")
    hide("prep_rate5")
    html("actionM5", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
})
observeEvent(input$actionM6, {
    disable("actionM6")
    hide("sep_exchange_frequency6")
    hide("sep_compliance6")
    hide("sep_start_time6")
    hide("art_start_time6")
    hide("art_number6")
    hide("art_rate6")
    hide("prep_number6")
    hide("prep_start_time6")
    hide("prep_rate6")
    html("actionM6", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
})
observeEvent(input$actionM7, {
    disable("actionM7")
    hide("sep_exchange_frequency7")
    hide("sep_compliance7")
    hide("sep_start_time7")
    hide("art_start_time7")
    hide("art_number7")
    hide("art_rate7")
    hide("prep_number7")
    hide("prep_start_time7")
    hide("prep_rate7")
    html("actionM7", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
})
observeEvent(input$actionM8, {
    disable("actionM8")
    hide("sep_exchange_frequency8")
    hide("sep_compliance8")
    hide("sep_start_time8")
    hide("art_start_time8")
    hide("art_number8")
    hide("art_rate8")
    hide("prep_number8")
    hide("prep_start_time8")
    hide("prep_rate8")
    html("actionM8", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
})
observeEvent(input$actionM9, {
    disable("actionM9")
    hide("sep_exchange_frequency9")
    hide("sep_compliance9")
    hide("sep_start_time9")
    hide("art_start_time9")
    hide("art_number9")
    hide("art_rate9")
    hide("prep_number9")
    hide("prep_start_time9")
    hide("prep_rate9")
    html("actionM9", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
})
observeEvent(input$actionM10, {
    disable("actionM10")
    hide("sep_exchange_frequency10")
    hide("sep_compliance10")
    hide("sep_start_time10")
    hide("art_start_time10")
    hide("art_number10")
    hide("art_rate10")
    hide("prep_number10")
    hide("prep_start_time10")
    hide("prep_rate10")
    html("actionM10", "<span class=\"glyphicon glyphicon-ok-sign\"></span>")
})

